'use client';

import { useMemo, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { api, ApiError } from '@/lib/api';
import { useT } from '@/lib/i18n';
import { usePreferences } from '@/lib/preferences';
import { Badge, Button, Card, EmptyState, ErrorState, LastUpdated, MapView, Modal, ProgressBar, Skeleton, StatusChip, Timeline, WorkFeature, toast } from '@/components/ui';

type Evidence={id?:string;public_url?:string;public_path?:string;taken_at?:string;kind?:string};
type Work={id:string;ref_no?:string;title:string;purpose?:string;category?:string;status:string;delayed?:boolean;update_overdue?:boolean;agency?:{id?:string;name:string};contractor_name?:string|null;contact?:{name?:string;phone_masked?:string;email?:string|null;channel?:string};road_name?:string;ward?:{id?:string;name?:string};geometry?:any;planned_start?:string;original_target_end?:string;current_target_end?:string;actual_start?:string;actual_end?:string;pct_complete?:number;milestones?:any[];disruption?:{type?:string;note?:string};last_update_at?:string;updates?:any[];date_revisions?:any[];status_history?:any[];evidence?:Evidence[];nearby_notices?:any[];still_ongoing?:{yes?:number;no?:number;last_confirmed_at?:string|null}};
const statusNames:Record<string,'planned'|'permitted'|'ongoing'|'paused'|'completed'|'restoration_verified'>={planned:'planned',permitted:'permitted',ongoing:'ongoing',paused:'paused',completed:'completed',restoration_verified:'restoration_verified'};
export default function WorkDetail(){
  const params=useParams<{id:string}>();const id=decodeURIComponent(params.id);const router=useRouter();const {t,language,formatDate}=useT();const {lowBandwidth}=usePreferences();const [photo,setPhoto]=useState<Evidence|null>(null);const [feedbackOpen,setFeedbackOpen]=useState(false);const [feedbackText,setFeedbackText]=useState('');const [feedbackKind,setFeedbackKind]=useState('observation');const [sending,setSending]=useState(false);
  const query=useQuery({queryKey:['work',id],queryFn:()=>api<Work>(`/works/${encodeURIComponent(id)}`)});const work=query.data;
  const statusLabel=work?.delayed?t('delayed'):t((statusNames[work?.status??'planned']??'planned') as any);
  const timeline=useMemo(()=>{
    if(!work)return[];const rows:any[]=[];
    (work.status_history??[]).forEach((item:any)=>rows.push({id:`s-${item.id??item.at}`,title:`${item.from_status?`${t(item.from_status as any)} → `:''}${t((item.to_status??item.status) as any)}`,detail:item.explanation??(item.reason_code?t(('reason_'+item.reason_code) as any):undefined), date:item.at,by:item.department??item.agency}));
    (work.date_revisions??[]).forEach((item:any)=>rows.push({id:`d-${item.id??item.at}`,title:`${t('revisedTarget')} ${formatDate(item.old_target)} → ${formatDate(item.new_target)}`,detail:`${t('reason')}: ${t(('reason_'+(item.reason_code??'other')) as any)}${item.explanation?` · ${item.explanation}`:''}`,date:item.at,by:item.department??item.agency}));
    (work.updates??[]).filter((item:any)=>item.is_public!==false).forEach((item:any)=>rows.push({id:`u-${item.id??item.at}`,title:item.text,detail:typeof item.pct_complete==='number'?`${t('progress')}: ${item.pct_complete}%`:undefined,date:item.at,by:item.department??item.agency}));
    (work.nearby_notices??[]).forEach((item:any,index:number)=>rows.push({id:`n-${index}`,title:item.text,detail:item.kind,date:item.at,by:item.department}));
    return rows.sort((a,b)=>new Date(b.date??0).getTime()-new Date(a.date??0).getTime());
  },[work,t,formatDate]);
  async function authenticatedAction(action:()=>Promise<any>,success:string){if(!localStorage.getItem('access_token')){router.push(`/login?next=${encodeURIComponent(`/works/${id}`)}`);return;}try{await action();toast(success);}catch(error){if(error instanceof ApiError&&(error.status===401||error.status===403)){router.push(`/login?next=${encodeURIComponent(`/works/${id}`)}`);return;}toast(error instanceof Error?error.message:t('error'));}}
  async function submitFeedback(event:React.FormEvent){event.preventDefault();if(!feedbackText.trim())return;setSending(true);await authenticatedAction(()=>api(`/works/${encodeURIComponent(id)}/feedback`,{method:'POST',body:JSON.stringify({kind:feedbackKind,text:feedbackText.trim()})}),t('feedbackSent'));setSending(false);setFeedbackText('');setFeedbackOpen(false);}
  if(query.isLoading)return <main className="page-wrap"><Skeleton className="skeleton-card"/></main>;
  if(query.isError||!work)return <main className="page-wrap"><ErrorState onRetry={()=>query.refetch()}/></main>;
  const geo={type:'FeatureCollection',features:work.geometry?[{type:'Feature',id:work.id,geometry:work.geometry,properties:{id:work.id,title:work.title,status:work.status,delayed:work.delayed,agency:work.agency?.name}}]:[]} as any;
  const revised=Boolean(work.current_target_end&&work.original_target_end&&work.current_target_end!==work.original_target_end);
  const evidence=(work.evidence??[]).filter(item=>item.public_url||item.public_path);
  const urls=(item:Evidence)=>item.public_url??(item.public_path?.startsWith('/')?item.public_path:`/files/${item.public_path}`);
  const structured=JSON.stringify({'@context':'https://schema.org','@type':'GovernmentService','name':work.title,'description':work.purpose??'Public infrastructure work','identifier':work.ref_no,'areaServed':work.ward?.name??'Demo City','provider':{'@type':'GovernmentOrganization','name':work.agency?.name},'url':`https://demo.city/works/${encodeURIComponent(id)}`}).replace(/</g,'\\u003c');
  return <main className="page-wrap">
    <script type="application/ld+json" dangerouslySetInnerHTML={{__html:structured}}/>
    <div className="detail-hero"><div className="detail-head"><div><span className="eyebrow">{work.ref_no??'Demo City'}</span><h1 className="page-title">{work.title}</h1><p className="page-lede">{work.purpose??t('noDescription')}</p><div className="status-summary"><StatusChip status={work.delayed?'delayed':work.status} label={statusLabel}/>{work.update_overdue&&<Badge tone="warning">! {t('updateOverdue')}</Badge>}</div><LastUpdated value={work.last_update_at}/></div><div className="detail-actions"><Button tone="secondary" onClick={async()=>{try{await navigator.clipboard.writeText(window.location.href);toast(t('shareCopied'));}catch{toast(window.location.href);}}}>↗ {t('share')}</Button><Button onClick={()=>authenticatedAction(()=>api('/follows',{method:'POST',body:JSON.stringify({work_id:id,channel:'console'})}),t('followed'))}>＋ {t('follow')}</Button></div></div></div>
    <div className="detail-grid"><div className="detail-column">
      <Card className="detail-card"><h2>{t('details')}</h2>{lowBandwidth ? <div className="low-data-note">{t('noMap')}</div> : <div className="detail-map"><MapView data={geo} height={230}/></div>}<p>{work.road_name??t('cityName')} · {work.ward?.name??''}</p><div className="section-head"><h2>{t('responsibleDepartment')}</h2></div><p><Link href={`/works?agency_id=${encodeURIComponent(work.agency?.id??'')}`}>{work.agency?.name??t('notProvided')}</Link></p>{work.contractor_name&&<p><strong>{t('contractor')}: </strong>{work.contractor_name}</p>}<div className="contact-block"><strong>{t('contact')}</strong><p>{work.contact?.name??t('notProvided')}</p><p>{work.contact?.channel??t('contactOffice')} {work.contact?.phone_masked?`· ${work.contact.phone_masked}`:''}</p><div className="contact-actions">{work.contact?.phone_masked&&<a className="ui-button ui-button-secondary" href={`tel:${work.contact.phone_masked.replace(/[^0-9+]/g,'')}`}>☎ {t('call')}</a>}{work.contact?.email&&<a className="ui-button ui-button-secondary" href={`mailto:${work.contact.email}`}>✉ {t('email')}</a>}</div></div></Card>
      <Card className="detail-card"><h2>{t('progress')}</h2><ProgressBar value={work.pct_complete??0} label={t('progress')}/><h3>{t('milestones')}</h3>{work.milestones?.length?work.milestones.map((m:any,index:number)=><div key={m.id??index} className="milestone"><div><strong>{m.name}</strong><small>{t('planned')}: {formatDate(m.planned_date)}</small></div><div>{m.actual_date&&<small>{t('completed')}: {formatDate(m.actual_date)}</small>}{typeof m.pct==='number'&&<span>{m.pct}%</span>}</div></div>):<p>{t('noMilestones')}</p>}</Card>
      <Card className="detail-card"><h2>{t('dates')}</h2><div className="date-grid"><div className="date-box"><small>{t('plannedStart')}</small><strong>{formatDate(work.planned_start)}</strong></div><div className="date-box"><small>{t('originalTarget')}</small><strong>{revised&&<del>{formatDate(work.original_target_end)}</del>}{!revised&&formatDate(work.original_target_end)}</strong></div><div className="date-box"><small>{t('revisedTarget')}</small><strong>{formatDate(work.current_target_end)}</strong></div></div></Card>
      {work.disruption&&work.disruption.type&&work.disruption.type!=='none'?<section className="disruption-box"><h3>⚠ {t('disruption')}</h3><p><strong>{t('disrupted')}: </strong>{t(('disruption_'+work.disruption.type) as any)}</p>{work.disruption.note&&<p>{work.disruption.note}</p>}</section>:<Card className="detail-card"><h2>{t('disruption')}</h2><p>{t('noDisruption')}</p></Card>}
      <Card className="detail-card"><h2>{t('recentUpdates')}</h2>{work.updates?.some((u:any)=>u.is_public!==false)?<div className="updates-feed">{work.updates.filter((u:any)=>u.is_public!==false).slice(0,5).map((item:any,index:number)=><article className="notice-item" key={item.id??index}><p>{item.text}</p><small>{formatDate(item.at)}{item.department?` · ${item.department}`:''}</small></article>)}</div>:<p>{t('noUpdates')}</p>}</Card>
      <Card className="detail-card"><h2>{t('progressPhotos')}</h2>{lowBandwidth?<p>{t('lowDataImages')}</p>:evidence.length?<div className="photo-grid">{evidence.map((item,index)=><button key={item.id??index} className="photo-button" onClick={()=>setPhoto(item)}><img src={urls(item)} alt={`${work.title} · ${item.kind??t('photos')} · ${formatDate(item.taken_at)}`} loading="lazy"/><span>{formatDate(item.taken_at)}</span></button>)}</div>:<p>{t('noPhotos')}</p>}</Card>
      <Card className="detail-card"><h2>{t('nearbyNotices')}</h2>{work.nearby_notices?.length?work.nearby_notices.map((notice:any,index:number)=><div className="notice-item" key={notice.id??index}><p>{notice.text}</p></div>):<p>{t('noNotices')}</p>}</Card>
      <Card className="detail-card"><h2>{t('stillOngoing')}</h2><p>{t('stillYes')}: <strong>{work.still_ongoing?.yes??0}</strong> · {t('stillNo')}: <strong>{work.still_ongoing?.no??0}</strong></p><div className="contact-actions"><Button tone="secondary" onClick={()=>authenticatedAction(()=>api(`/works/${encodeURIComponent(id)}/still-ongoing`,{method:'POST',body:JSON.stringify({value:true})}),t('thanks'))}>✓ {t('yes')}</Button><Button tone="secondary" onClick={()=>authenticatedAction(()=>api(`/works/${encodeURIComponent(id)}/still-ongoing`,{method:'POST',body:JSON.stringify({value:false})}),t('thanks'))}>× {t('no')}</Button></div></Card>
      <Card className="detail-card"><h2>{t('timeline')}</h2>{timeline.length?<Timeline items={timeline}/>:<p>{t('noUpdates')}</p>}</Card>
    </div><aside className="detail-column"><Card className="detail-card"><div className="section-head" style={{marginTop:0}}><h2>{t('feedbackTitle')}</h2></div><Button onClick={()=>setFeedbackOpen(true)}>✎ {t('feedback')}</Button><p>{t('signInToFollow')}</p></Card><LastUpdated value={work.last_update_at}/></aside></div>
    <Modal open={!!photo} title={work.title} onClose={()=>setPhoto(null)}>{photo&&<figure><img src={urls(photo)} alt={`${work.title} · ${photo.kind??t('photos')}`} style={{width:'100%',maxHeight:'70vh',objectFit:'contain'}}/><figcaption>{t('photos')} · {formatDate(photo.taken_at)}</figcaption></figure>}</Modal>
    <Modal open={feedbackOpen} title={t('feedbackTitle')} onClose={()=>setFeedbackOpen(false)}><form className="feedback-form" onSubmit={submitFeedback}><label className="form-label" htmlFor="feedback-kind">{t('feedbackKind')}</label><select className="ui-input" id="feedback-kind" value={feedbackKind} onChange={e=>setFeedbackKind(e.target.value)}><option value="observation">{t('observation')}</option><option value="question">{t('question')}</option><option value="complaint">{t('complaint')}</option></select><label className="form-label" htmlFor="feedback-text">{t('feedbackText')}</label><textarea className="ui-input ui-textarea" id="feedback-text" value={feedbackText} onChange={e=>setFeedbackText(e.target.value)} required/><Button type="submit" disabled={sending}>{sending?t('loading'):t('submit')}</Button></form></Modal>
  </main>;
}
