'use client';

import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import { Badge, Card, EmptyState, ErrorState, MapView, Skeleton, StatusChip, WorkFeature } from '@/components/ui';
import { Bar,BarChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis } from 'recharts';
import { StaffNav } from '@/components/staff/StaffNav';

type Summary={ongoing:number;delayed:number;overdue_updates:number;completed_this_month:number;total:number};
type Inbox={works:{kind:string;id:string;ref_no:string;title:string;road_name?:string;ward_name?:string;due_at?:string;status:string}[];feedback:{id:string;ref_no:string;kind:string;current_level:number;title:string;road_name?:string;possibly_stale_data:boolean}[];conflicts:{id:string;kind:string;title:string;road_name?:string}[]};
type Repeat={road_name?:string;ward_name?:string;work_count:number;works:{id:string;ref_no:string;title:string;agency:string}[]};
type Work={status:string;agency:{name:string}};
type Geo={type:'FeatureCollection';features:WorkFeature[]};

export default function StaffDashboardPage(){const [summary,setSummary]=useState<Summary|null>(null);const [inbox,setInbox]=useState<Inbox|null>(null);const [repeat,setRepeat]=useState<Repeat[]>([]);const [works,setWorks]=useState<Work[]>([]);const [geo,setGeo]=useState<Geo|null>(null);const [selectedRoad,setSelectedRoad]=useState('');const [failed,setFailed]=useState(false);
 useEffect(()=>{Promise.all([api<Summary>('/reports/summary'),api<Inbox>('/staff/inbox'),api<{items:Repeat[]}>('/reports/repeat-dig'),api<{items:Work[]}>('/works?page_size=100'),api<Geo>('/works/geojson')]).then(([s,i,r,w,g])=>{setSummary(s);setInbox(i);setRepeat(r.items);setWorks(w.items);setGeo(g)}).catch(()=>setFailed(true))},[]);
 const statusCounts=useMemo(()=>works.reduce<Record<string,number>>((a,w)=>(a[w.status]=(a[w.status]||0)+1,a),{}),[works]);const agencyCounts=useMemo(()=>works.reduce<Record<string,number>>((a,w)=>(a[w.agency.name]=(a[w.agency.name]||0)+1,a),{}),[works]);const hotFeatures=useMemo(()=>({type:'FeatureCollection' as const,features:(geo?.features||[]).filter(f=>!selectedRoad||f.properties.road_name===selectedRoad)}),[geo,selectedRoad]);
 return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow">Staff console · Operations overview</p><div className="staff-heading"><div><h1 className="page-title">Dashboard</h1><p className="page-lede">A jurisdiction-scoped view of delivery risks and resident accountability.</p></div><a className="ui-button ui-button-secondary" href="/staff/feedback">Open feedback inbox</a></div>
 {failed&&<ErrorState onRetry={()=>location.reload()}/>} {!summary||!inbox?<div className="staff-kpis">{[1,2,3,4,5].map(n=><Skeleton key={n} className="skeleton-card"/>)}</div>:<><section className="staff-kpis"><Card><span>Open conflicts</span><strong>{inbox.conflicts.length}</strong></Card><Card><span>Delayed works</span><strong>{summary.delayed}</strong></Card><Card><span>Overdue updates</span><strong>{summary.overdue_updates}</strong></Card><Card><span>Tickets awaiting</span><strong>{inbox.feedback.length}</strong></Card><Card><span>Repeat-dig segments</span><strong>{repeat.length}</strong></Card></section>
 <div className="staff-dashboard-grid"><Card><h2>Works by status</h2><div className="staff-chart" role="img" aria-label="Bar chart showing the number of works by status"><ResponsiveContainer width="100%" height={240}><BarChart data={Object.entries(statusCounts).map(([name,count])=>({name:name.replaceAll('_',' '),count}))} margin={{top:8,right:8,left:-18,bottom:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:11}} interval={0}/><YAxis allowDecimals={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" name="Works" fill="#087e8b" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card><h2>Works by agency</h2><div className="staff-chart" role="img" aria-label="Bar chart showing the number of works by agency"><ResponsiveContainer width="100%" height={240}><BarChart data={Object.entries(agencyCounts).sort((a,b)=>b[1]-a[1]).slice(0,7).map(([name,count])=>({name,count}))} margin={{top:8,right:8,left:-18,bottom:8}}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name" tick={{fontSize:10}} interval={0}/><YAxis allowDecimals={false} tick={{fontSize:11}}/><Tooltip/><Bar dataKey="count" name="Works" fill="#315a8c" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card></div>
 <section className="staff-dashboard-grid"><Card><h2>Staff inbox</h2>{inbox.works.length+inbox.feedback.length+inbox.conflicts.length===0?<EmptyState title="Inbox clear"/>:<ul className="staff-inbox">{inbox.feedback.slice(0,5).map(t=><li key={t.id}><Badge tone="warning">Level {t.current_level}</Badge>{t.possibly_stale_data&&<Badge tone="danger">Possibly stale data</Badge>}<a href="/staff/feedback">{t.ref_no} · {t.title}</a><span>{t.road_name||t.kind}</span></li>)}{inbox.works.slice(0,7).map((w,i)=><li key={`${w.kind}-${w.id}-${i}`}><Badge tone="danger">{w.kind.replaceAll('_',' ')}</Badge><a href={`/works/${w.id}`}>{w.ref_no} · {w.title}</a><span>{w.road_name||w.status}</span></li>)}{inbox.conflicts.slice(0,5).map(c=><li key={c.id}><Badge tone="danger">Conflict</Badge><a href={`/staff/conflicts/${c.id}`}>{c.title}</a><span>{c.road_name}</span></li>)}</ul>}</Card><Card><h2>Repeat-dig hotspots</h2>{repeat.length===0?<EmptyState title="No repeat-dig segments"/>:<><div className="table-responsive"><table className="summary-table"><thead><tr><th>Road / ward</th><th>Works</th><th></th></tr></thead><tbody>{repeat.map((item,index)=><tr key={`${item.road_name}-${index}`}><td>{item.road_name||'Unnamed road'}<small className="table-subline">{item.ward_name}</small></td><td>{item.work_count}</td><td><button className="staff-text-button" onClick={()=>setSelectedRoad(item.road_name||'')}>Highlight map</button></td></tr>)}</tbody></table></div><div className="staff-hotspot-map">{geo&&<MapView data={hotFeatures} height={260}/>}</div></>}</Card></section></>}</main>
}
