'use client';

import { ButtonHTMLAttributes, InputHTMLAttributes, SelectHTMLAttributes, TextareaHTMLAttributes, ReactNode, useEffect, useState } from 'react';
import { useT } from '@/lib/i18n';
export { MapView } from './MapView';
export type { WorkFeature, WorkProperties } from './MapView';

type Tone = 'primary' | 'secondary' | 'quiet' | 'danger';
export function Button({ tone = 'primary', className = '', ...props }: ButtonHTMLAttributes<HTMLButtonElement> & { tone?: Tone }) { return <button className={`ui-button ui-button-${tone} ${className}`} {...props} />; }
export function Input(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} className={`ui-input ${props.className ?? ''}`} />; }
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={`ui-input ${props.className ?? ''}`} />; }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={`ui-input ui-textarea ${props.className ?? ''}`} />; }
export function Card({ children, className = '', ...props }: React.HTMLAttributes<HTMLDivElement>) { return <section className={`ui-card ${className}`} {...props}>{children}</section>; }

const statusNames: Record<string, string> = { planned: 'Planned', permitted: 'Permitted', ongoing: 'Ongoing', paused: 'Paused', completed: 'Completed', restoration_verified: 'Restoration verified', closed: 'Closed', delayed: 'Delayed', update_overdue: 'Update overdue' };
const statusIcons: Record<string, string> = { planned: '◷', permitted: '✓', ongoing: '●', paused: 'Ⅱ', completed: '✓', restoration_verified: '◆', closed: '✓', delayed: '!', update_overdue: '!' };
export function Badge({ children, tone = 'neutral' }: { children: ReactNode; tone?: string }) { return <span className={`ui-badge ui-badge-${tone}`}>{children}</span>; }
export function StatusChip({ status, label }: { status: string; label?: string }) { const name = label ?? statusNames[status] ?? status.replaceAll('_', ' '); return <span className={`status-chip status-${status}`}><span aria-hidden="true" className="status-icon">{statusIcons[status] ?? '•'}</span>{name}</span>; }

export function Tabs<T extends string>({ items, value, onChange }: { items: { id: T; label: string }[]; value: T; onChange: (id: T) => void }) { return <div className="ui-tabs" role="tablist">{items.map((item) => <button key={item.id} role="tab" aria-selected={value === item.id} className={value === item.id ? 'active' : ''} onClick={() => onChange(item.id)}>{item.label}</button>)}</div>; }
export function Modal({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { const {t}=useT();useEffect(() => { if (!open) return; const handler = (event: KeyboardEvent) => { if (event.key === 'Escape') onClose(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [open, onClose]); if (!open) return null; return <div className="modal-backdrop" onMouseDown={(e) => { if (e.target === e.currentTarget) onClose(); }}><section role="dialog" aria-modal="true" aria-label={title} className="ui-modal"><header><h2>{title}</h2><Button tone="quiet" aria-label={t('close')} onClick={onClose}>×</Button></header>{children}</section></div>; }
export function Drawer({ open, title, children, onClose }: { open: boolean; title: string; children: ReactNode; onClose: () => void }) { const {t}=useT();return <div className={`drawer-wrap ${open ? 'drawer-open' : ''}`} aria-hidden={!open}><button className="drawer-scrim" tabIndex={open ? 0 : -1} aria-label={t('close')} onClick={onClose} /><section className="ui-drawer" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><Button tone="quiet" aria-label={t('close')} onClick={onClose}>×</Button></header>{children}</section></div>; }
export function Toast({ message, onClose }: { message: string; onClose: () => void }) { const {t}=useT();useEffect(() => { const timer = window.setTimeout(onClose, 2800); return () => window.clearTimeout(timer); }, [message, onClose]); return <div role="status" className="ui-toast">{message}<button aria-label={t('close')} onClick={onClose}>×</button></div>; }
export function ToastProvider({ children }: { children: ReactNode }) { const [message, setMessage] = useState(''); useEffect(() => { const handler = (event: Event) => setMessage((event as CustomEvent<string>).detail); window.addEventListener('app-toast', handler); return () => window.removeEventListener('app-toast', handler); }, []); return <>{children}{message && <Toast message={message} onClose={() => setMessage('')} />}</>; }
export function toast(message: string) { if (typeof window !== 'undefined') window.dispatchEvent(new CustomEvent('app-toast', { detail: message })); }
export function Skeleton({ className = '' }: { className?: string }) { return <div aria-hidden="true" className={`ui-skeleton ${className}`} />; }
export function EmptyState({ title, detail, action }: { title: string; detail?: string; action?: ReactNode }) { return <div className="ui-state"><span aria-hidden="true" className="state-icon">⌕</span><h2>{title}</h2>{detail && <p>{detail}</p>}{action}</div>; }
export function ErrorState({ onRetry }: { onRetry?: () => void }) { const { t } = useT(); return <div className="ui-state error-state"><span aria-hidden="true" className="state-icon">!</span><h2>{t('error')}</h2>{onRetry && <Button tone="secondary" onClick={onRetry}>{t('retry')}</Button>}</div>; }

export function LastUpdated({ value, className = '' }: { value?: string | null; className?: string }) { const { language, t, formatDate, formatRelative } = useT(); if (!value) return null; const date = new Date(value); const absolute = new Intl.DateTimeFormat(language === 'hi' ? 'hi-IN' : 'en-IN', { day: '2-digit', month: 'short', year: 'numeric', hour: 'numeric', minute: '2-digit' }).format(date); return <span className={`last-updated ${className}`} title={absolute}>{t('lastUpdated')}: {formatRelative(value)} · {absolute}</span>; }
export function Timeline({ items }: { items: { id?: string | number; title: string; detail?: string; date?: string | null; by?: string }[] }) { const { formatDate } = useT(); return <ol className="ui-timeline">{items.map((item, index) => <li key={item.id ?? index}><span className="timeline-dot" /><div><h3>{item.title}</h3>{item.detail && <p>{item.detail}</p>}<small>{formatDate(item.date)}{item.by ? ` · ${item.by}` : ''}</small></div></li>)}</ol>; }
export function ProgressBar({ value = 0, label }: { value?: number; label?: string }) { const progress = Math.max(0, Math.min(100, value)); return <div className="progress-wrap"><div className="progress-label"><strong>{label ?? 'Progress'}</strong><span>{progress}%</span></div><div className="progress-track" role="progressbar" aria-valuenow={progress} aria-valuemin={0} aria-valuemax={100}><span style={{ width: `${progress}%` }} /></div></div>; }
export function Pagination({ page, pageSize, total, onPage }: { page: number; pageSize: number; total: number; onPage: (next: number) => void }) { const { t } = useT(); const pages = Math.max(1, Math.ceil(total / pageSize)); return <nav className="ui-pagination" aria-label="Pagination"><Button tone="secondary" disabled={page <= 1} onClick={() => onPage(page - 1)}>← {t('previous')}</Button><span>{t('page')} {page} {t('of')} {pages}</span><Button tone="secondary" disabled={page >= pages} onClick={() => onPage(page + 1)}>{t('next')} →</Button></nav>; }

