'use client';

import { useCallback, useEffect, useState } from 'react';
import { api } from '@/lib/api';
import { Badge, Button, Card, Drawer, EmptyState, ErrorState, Input, Select, Skeleton, StatusChip, Textarea } from '@/components/ui';
import { StaffNav } from '@/components/staff/StaffNav';

type Ticket={id:string;ref_no:string;work_id:string;work_ref_no:string;work_title:string;road_name?:string;kind:string;text:string;status:string;current_level:number;created_at:string;escalated_at?:string|null;last_response_at?:string|null;overdue_public:boolean;moderation:string;history:{id:string;status:string;message?:string|null;is_public:boolean;at:string}[];sla_age_days:number;awaiting_response:boolean;possibly_stale_data:boolean;resident_name:string};
const roles:Record<number,string>={1:'JE',2:'AE',3:'EE',4:'SE'};

export default function StaffFeedbackPage(){
  const [items,setItems]=useState<Ticket[]>([]);const [selected,setSelected]=useState<Ticket|null>(null);const [message,setMessage]=useState('');const [status,setStatus]=useState('in_progress');const [makePublic,setMakePublic]=useState(false);const [filter,setFilter]=useState('awaiting');const [loading,setLoading]=useState(true);const [error,setError]=useState(false);const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{setLoading(true);setError(false);try{const q=filter==='awaiting'?'?awaiting=true':filter==='all'?'':'?status=open';const data=await api<{items:Ticket[]}>(`/staff/feedback${q}`);setItems(data.items);if(selected){setSelected(data.items.find(x=>x.id===selected.id)??null)}}catch{setError(true)}finally{setLoading(false)}},[filter,selected]);
  useEffect(()=>{void load()},[filter]);
  async function respond(){if(!selected||!message.trim())return;setBusy(true);try{await api(`/staff/feedback/${selected.id}/respond`,{method:'POST',body:JSON.stringify({message,status,make_public:makePublic})});setMessage('');await load()}catch{setError(true)}finally{setBusy(false)}}
  async function moderate(approve:boolean){if(!selected)return;setBusy(true);try{await api(`/staff/feedback/${selected.id}/moderate`,{method:'POST',body:JSON.stringify({approve})});await load()}catch{setError(true)}finally{setBusy(false)}}
  return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow">Staff console · Resident accountability</p><div className="staff-heading"><div><h1 className="page-title">Feedback inbox</h1><p className="page-lede">Review resident reports by SLA age, respond, and moderate messages for public display.</p></div><Button tone="secondary" onClick={()=>void load()}>Refresh inbox</Button></div>
    <div className="staff-toolbar"><Select aria-label="Feedback filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="awaiting">Awaiting response</option><option value="all">All tickets</option><option value="open">Open tickets</option></Select><span>{items.length} tickets</span></div>
    {error&&<ErrorState onRetry={()=>void load()}/>}{loading?<div className="staff-list">{[1,2,3].map(n=><Skeleton key={n} className="skeleton-card"/>)}</div>:items.length===0?<Card><EmptyState title="No feedback in this view" detail="New resident reports will appear here."/></Card>:<div className="staff-ticket-grid">{items.map(ticket=><Card key={ticket.id} className="staff-ticket"><div className="staff-ticket-top"><Badge tone={ticket.awaiting_response?'warning':'neutral'}>{ticket.awaiting_response?'Awaiting response':ticket.status}</Badge><Badge>Level {ticket.current_level} · {roles[ticket.current_level]}</Badge>{ticket.escalated_at&&<Badge tone="danger">Escalated</Badge>}</div><h2>{ticket.ref_no} · {ticket.kind.replaceAll('_',' ')}</h2><p>{ticket.text}</p><div className="staff-meta"><a href={`/works/${ticket.work_id}`}>{ticket.work_ref_no} · {ticket.work_title}</a><span>{ticket.road_name||'Location pending'} · {ticket.sla_age_days.toFixed(1)} SLA days</span></div>{ticket.possibly_stale_data&&<p className="staff-alert">Possibly stale data: 3 or more residents reported this ongoing work may have stopped.</p>}<Button tone="secondary" onClick={()=>setSelected(ticket)}>Review ticket</Button></Card>)}</div>}
    <Drawer open={!!selected} title={selected?`Ticket ${selected.ref_no}`:'Ticket'} onClose={()=>setSelected(null)}>{selected&&<div className="staff-drawer-content"><Badge>Level {selected.current_level} · {roles[selected.current_level]}</Badge>{selected.escalated_at&&<Badge tone="danger">Escalated</Badge>}<p>{selected.text}</p><p><a href={`/works/${selected.work_id}`}>{selected.work_ref_no} · {selected.work_title}</a></p><p><strong>Resident:</strong> {selected.resident_name}</p><h3>Status history</h3><ol className="staff-history">{selected.history.map(event=><li key={event.id}><strong>{event.status.replaceAll('_',' ')}</strong><span>{event.message||'Status updated'}{event.is_public?' · public':''}</span><time>{new Date(event.at).toLocaleString('en-IN')}</time></li>)}</ol><div className="form-field"><label className="form-label" htmlFor="staff-response">Response to resident</label><Textarea id="staff-response" maxLength={2000} value={message} onChange={e=>setMessage(e.target.value)} placeholder="Write a clear update for the resident"/></div><div className="form-field"><label className="form-label" htmlFor="response-status">Ticket status</label><Select id="response-status" value={status} onChange={e=>setStatus(e.target.value)}><option value="acknowledged">Acknowledged</option><option value="in_progress">In progress</option><option value="resolved">Resolved</option><option value="closed">Closed</option></Select></div><label className="staff-checkbox"><input type="checkbox" checked={makePublic} onChange={e=>setMakePublic(e.target.checked)}/> Publish this response after moderation</label><Button disabled={busy||!message.trim()} onClick={()=>void respond()}>Send response</Button><hr/><h3>Public moderation</h3><p>Only approved tickets with public visibility appear on the work page. Personal details are removed from public text.</p><div className="link-row"><Button disabled={busy} onClick={()=>void moderate(true)}>Approve public display</Button><Button tone="danger" disabled={busy} onClick={()=>void moderate(false)}>Reject</Button></div></div>}</Drawer>
  </main>
}
