'use client';

import { useParams } from 'next/navigation';
import { useEffect,useState } from 'react';
import { api } from '@/lib/api';
import { Badge,Button,Card,ErrorState,Input,Select,Skeleton,StatusChip,Textarea,Timeline } from '@/components/ui';
import { ConflictMap } from '@/components/staff/ConflictMap';
import { StaffNav } from '@/components/staff/StaffNav';

type Work={id:string;ref_no:string;title:string;purpose?:string;agency:{name:string};road_name?:string;ward?:{name:string};planned_start?:string;current_target_end?:string;contact?:{name?:string;phone_masked?:string;email?:string};geometry:GeoJSON.Geometry};
type Detail={id:string;type:string;status:string;overlap_days?:number;days_since_resurfacing?:number;work_a:Work;work_b:Work;overlap?:{geometry?:GeoJSON.Geometry;start?:string;end?:string};history:{id?:string;title:string;detail?:string;at?:string;by?:string}[];buffer_geometry_a?:GeoJSON.Geometry;buffer_geometry_b?:GeoJSON.Geometry};
const actions=[['coordinate_dates','Coordinate dates'],['combine_work','Combine work'],['reschedule','Reschedule'],['justify_both','Justify both']];
export default function ConflictDetail(){const params=useParams<{id:string}>();const [detail,setDetail]=useState<Detail|null>(null);const [error,setError]=useState(false);const [action,setAction]=useState('coordinate_dates');const [note,setNote]=useState('');const [workId,setWorkId]=useState('');const [start,setStart]=useState('');const [end,setEnd]=useState('');const [busy,setBusy]=useState(false);
 async function load(){try{setDetail(await api<Detail>(`/conflicts/${params.id}`));setError(false)}catch{setError(true)}}useEffect(()=>{void load()},[params.id]);
 async function decide(){if(!detail||note.trim().length<15)return;setBusy(true);try{await api(`/conflicts/${detail.id}/decision`,{method:'POST',body:JSON.stringify({action,note,work_id:workId||undefined,new_dates:start&&end?{planned_start:start,current_target_end:end}:undefined,reason_code:'utility_clash'})});await load()}catch{setError(true)}finally{setBusy(false)}}
 if(error)return <main className="page-wrap staff-console"><StaffNav/><ErrorState onRetry={()=>void load()}/></main>;if(!detail)return <main className="page-wrap staff-console"><StaffNav/><Skeleton className="skeleton-card"/></main>;
 const selected=workId||detail.work_a.id;return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow"><a href="/staff/conflicts">Conflicts</a> · Coordination detail</p><div className="staff-heading"><div><h1 className="page-title">{detail.work_a.road_name||detail.work_b.road_name||'Work coordination'}</h1><p className="page-lede">Review the overlap and record a decision. The system will not cancel or approve work automatically.</p></div><StatusChip status={detail.status==='resolved'?'completed':'delayed'} label={detail.status}/></div><Card><div className="staff-ticket-top"><StatusChip status={detail.type==='overlap'?'delayed':'update_overdue'} label={detail.type==='overlap'?'Overlap':'Recently resurfaced'}/><Badge>{detail.type==='overlap'?`${detail.overlap_days??0} overlap days`:`${detail.days_since_resurfacing??'—'} days since resurfacing`}</Badge></div>{detail.overlap?.start&&<p>Overlap window: {detail.overlap.start} – {detail.overlap.end}</p>}<ConflictMap a={detail.work_a.geometry} b={detail.work_b.geometry} bufferA={detail.buffer_geometry_a} bufferB={detail.buffer_geometry_b}/><div className="staff-project-pair"><Project work={detail.work_a} tone="blue"/><Project work={detail.work_b} tone="orange"/></div></Card>
 <section className="staff-dashboard-grid"><Card><h2>Decision</h2><div className="form-field"><label className="form-label" htmlFor="conflict-action">Resolution</label><Select id="conflict-action" value={action} onChange={e=>setAction(e.target.value)}>{actions.map(([value,label])=><option key={value} value={value}>{label}</option>)}</Select></div>{action!=='justify_both'&&<div className="form-field"><label className="form-label" htmlFor="chosen-work">Work to update</label><Select id="chosen-work" value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">Select work</option><option value={detail.work_a.id}>{detail.work_a.ref_no}</option><option value={detail.work_b.id}>{detail.work_b.ref_no}</option></Select></div>}{['coordinate_dates','reschedule'].includes(action)&&<div className="date-grid"><div className="form-field"><label className="form-label">New start</label><Input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="form-field"><label className="form-label">New target end</label><Input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div>}<div className="form-field"><label className="form-label" htmlFor="decision-note">Decision note (minimum 15 characters)</label><Textarea id="decision-note" maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Explain the coordination decision and its public impact."/></div><Button disabled={busy||note.trim().length<15||detail.status==='resolved'} onClick={()=>void decide()}>Record decision</Button></Card><Card><h2>Decision history</h2>{detail.history.length?<Timeline items={detail.history.map((h,i)=>({id:h.id??i,title:h.title,detail:h.detail,date:h.at,by:h.by}))}/>:<p>No decisions recorded.</p>}</Card></section></main>
}
function Project({work,tone}:{work:Work;tone:string}){return <article className={`staff-project-detail ${tone}`}><span className="eyebrow">{work.agency?.name}</span><h2>{work.ref_no} · {work.title}</h2><p>{work.purpose||work.road_name||work.ward?.name}</p><p>Schedule: {work.planned_start||'Pending'} → {work.current_target_end||'Pending'}</p><p>Contact: {work.contact?.name||'Office'} · {work.contact?.phone_masked||work.contact?.email||'Contact channel in permit record'}</p></article>}
