'use client';

import { useEffect,useState } from 'react';
import { api } from '@/lib/api';
import { Badge,Button,Card,EmptyState,ErrorState,Skeleton,StatusChip,Tabs } from '@/components/ui';
import { StaffNav } from '@/components/staff/StaffNav';

type Conflict={id:string;type:string;status:string;overlap_days?:number;days_since_resurfacing?:number;detected_at:string;work_a:{id:string;title:string;ref_no:string;agency:{name:string};road_name?:string;planned_start?:string;current_target_end?:string};work_b:{id:string;title:string;ref_no:string;agency:{name:string};road_name?:string;planned_start?:string;current_target_end?:string}};
export default function StaffConflicts(){const [tab,setTab]=useState<'open'|'resolved'>('open');const [items,setItems]=useState<Conflict[]>([]);const [error,setError]=useState(false);const [loading,setLoading]=useState(true);useEffect(()=>{setLoading(true);api<{items:Conflict[]}>(`/conflicts?status=${tab}`).then(x=>setItems(x.items)).catch(()=>setError(true)).finally(()=>setLoading(false))},[tab]);
 return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow">Staff console · Coordination</p><div className="staff-heading"><div><h1 className="page-title">Utility conflicts</h1><p className="page-lede">Resolve overlapping work schedules and recently resurfaced roads through documented coordination.</p></div></div><Tabs items={[{id:'open',label:'Open alerts'},{id:'resolved',label:'Resolved'}]} value={tab} onChange={setTab}/>{error&&<ErrorState onRetry={()=>location.reload()}/>}<div className="staff-conflict-list">{loading?[1,2,3].map(n=><Skeleton key={n} className="skeleton-card"/>):items.length===0?<Card><EmptyState title={`No ${tab} alerts`} detail="Conflict alerts appear after a permit submission or scan."/></Card>:items.map(c=><Card key={c.id} className="staff-conflict-card"><div className="staff-ticket-top"><StatusChip status={c.type==='overlap'?'delayed':'update_overdue'} label={c.type==='overlap'?'Overlap':'Recently resurfaced'}/>{c.status==='open'&&<Badge tone="warning">Needs decision</Badge>}</div><h2>{c.work_a.road_name||c.work_b.road_name||'Work area'}</h2><div className="staff-project-pair"><ProjectCard work={c.work_a}/><span className="pair-mark">↔</span><ProjectCard work={c.work_b}/></div><p>{c.type==='overlap'?`${c.overlap_days??0} overlapping calendar days`:`Resurfaced ${c.days_since_resurfacing??'—'} days before this work`}</p><a className="ui-button ui-button-primary" href={`/staff/conflicts/${c.id}`}>Open coordination detail</a></Card>)}</div></main>
}
function ProjectCard({work}:{work:Conflict['work_a']}){return <div className="staff-project-card"><strong>{work.ref_no} · {work.title}</strong><span>{work.agency?.name}</span><small>{work.planned_start||'Start pending'} → {work.current_target_end||'End pending'}</small></div>}
