'use client';

import { useParams } from 'next/navigation';
import { useEffect,useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { Badge,Button,Card,ErrorState,Skeleton,Textarea } from '@/components/ui';
import { StaffNav } from '@/components/staff/StaffNav';

type Permit={id:string;work_id:string;type:string;status:string;work:{id:string;ref_no:string;title:string;road_name?:string;status:string;planned_start?:string;current_target_end?:string;agency:{name:string}};conflicts:{id:string;type:string;status:string;work_ref?:string}[];deposit_amount?:number;deposit_status:string;restoration_verified:boolean;valid_from?:string;valid_to?:string;history:{title:string;detail?:string;at?:string;by?:string}[]};
export default function PermitDetail(){const {id}=useParams<{id:string}>();const [permit,setPermit]=useState<Permit|null>(null);const [error,setError]=useState(false);const [note,setNote]=useState('');const [busy,setBusy]=useState(false);async function load(){try{setPermit(await api<Permit>(`/permits/${id}`));setError(false)}catch{setError(true)}}useEffect(()=>{void load()},[id]);async function decision(action:string){if(!permit)return;setBusy(true);try{await api(`/permits/${permit.id}/decision`,{method:'POST',body:JSON.stringify({action,note})});await load()}catch{setError(true)}finally{setBusy(false)}}async function release(){if(!permit)return;setBusy(true);try{await api(`/permits/${permit.id}/deposit/release`,{method:'POST',body:JSON.stringify({note})});await load()}catch{setError(true)}finally{setBusy(false)}}
 if(error)return <main className="page-wrap staff-console"><StaffNav/><ErrorState onRetry={()=>void load()}/></main>;if(!permit)return <main className="page-wrap staff-console"><StaffNav/><Skeleton className="skeleton-card"/></main>;const blocked=permit.status==='pending_coordination'||permit.conflicts.some(c=>c.status==='open');
 return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow"><Link href="/staff/permits">Permits</Link> · Review</p><div className="staff-heading"><div><h1 className="page-title">{permit.work.ref_no} · {permit.type.replaceAll('_',' ')}</h1><p className="page-lede">{permit.work.title} · {permit.work.agency.name}</p></div><Badge>{permit.status.replaceAll('_',' ')}</Badge></div>{blocked&&<Card className="staff-alert-card"><h2>Coordination required before approval</h2><p>This permit is blocked because an open conflict involves the registered work. The permit can be approved after every conflict is resolved.</p>{permit.conflicts.map(c=><p key={c.id}><Link href={`/staff/conflicts/${c.id}`}>{c.type.replaceAll('_',' ')} · Resolve alert</Link></p>)}</Card>}<section className="staff-dashboard-grid"><Card><h2>Registered work</h2><p><Link href={`/works/${permit.work.id}`}>{permit.work.ref_no} · {permit.work.title}</Link></p><p>{permit.work.road_name} · {permit.work.status}</p><p>Schedule: {permit.work.planned_start||'—'} → {permit.work.current_target_end||'—'}</p><p>Permit dates: {permit.valid_from||'—'} → {permit.valid_to||'—'}</p>{permit.type==='closure_noc'&&<Badge tone="warning">Closure NOC · traffic_police approval required</Badge>}</Card><Card><h2>Deposit and restoration</h2><p>Deposit: {permit.deposit_amount==null?'Not set':`₹${permit.deposit_amount.toLocaleString('en-IN')}`}</p><p>Status: {permit.deposit_status}</p><p>Restoration verified: {permit.restoration_verified?'Yes':'No'}</p>{permit.deposit_status==='held'&&<Button disabled={busy||!permit.restoration_verified} onClick={()=>void release()}>Release deposit</Button>}{permit.deposit_status==='held'&&!permit.restoration_verified&&<small>Deposit release becomes available after restoration verification.</small>}</Card></section><section className="staff-dashboard-grid"><Card><h2>Decision</h2><label className="form-label" htmlFor="permit-note">Decision note</label><Textarea id="permit-note" value={note} onChange={e=>setNote(e.target.value)} maxLength={1000} placeholder="Explain the decision for the record."/><div className="link-row"><Button disabled={busy||blocked||!note.trim()} onClick={()=>void decision('approve')}>Approve</Button><Button tone="secondary" disabled={busy||!note.trim()} onClick={()=>void decision('hold')}>Hold</Button><Button tone="danger" disabled={busy||!note.trim()} onClick={()=>void decision('reject')}>Reject</Button></div></Card><Card><h2>Permit history</h2>{permit.history.length?permit.history.map((h,i)=><div className="staff-history-row" key={i}><strong>{h.title}</strong><p>{h.detail}</p><small>{h.at?new Date(h.at).toLocaleString('en-IN'):''} · {h.by}</small></div>):<p>No permit events recorded.</p>}</Card></section></main>
}
