'use client';

import { useEffect,useState } from 'react';
import Link from 'next/link';
import { api } from '@/lib/api';
import { Badge,Button,Card,EmptyState,ErrorState,Input,Select,Skeleton,Tabs,Textarea } from '@/components/ui';
import { StaffNav } from '@/components/staff/StaffNav';

type Permit={id:string;work_id:string;work_ref_no:string;work_title:string;agency_name:string;type:string;status:string;applied_at:string;valid_from?:string;valid_to?:string;deposit_amount?:number;deposit_status:string;has_open_conflict:boolean;conflict_summary?:string};
type Work={id:string;ref_no:string;title:string;road_name?:string};
const statuses=['draft','submitted','pending_coordination','approved'];
export default function StaffPermits(){const [tab,setTab]=useState('draft');const [items,setItems]=useState<Permit[]>([]);const [works,setWorks]=useState<Work[]>([]);const [showApply,setShowApply]=useState(false);const [workId,setWorkId]=useState('');const [type,setType]=useState('road_cut');const [from,setFrom]=useState('');const [to,setTo]=useState('');const [note,setNote]=useState('');const [error,setError]=useState(false);const [busy,setBusy]=useState(false);
 async function load(){setError(false);try{const [p,w]=await Promise.all([api<{items:Permit[]}>(`/permits?status=${tab}`),api<{items:Work[]}>('/works?page_size=100')]);setItems(p.items);setWorks(w.items)}catch{setError(true)}}useEffect(()=>{void load()},[tab]);
 async function apply(){if(!workId)return;setBusy(true);try{const p=await api<{id:string}>('/permits',{method:'POST',body:JSON.stringify({work_id:workId,type,valid_from:from||undefined,valid_to:to||undefined,note:note||undefined})});location.href=`/staff/permits/${p.id}`}catch{setError(true)}finally{setBusy(false)}}
 return <main className="page-wrap staff-console"><StaffNav/><p className="eyebrow">Staff console · Right of way</p><div className="staff-heading"><div><h1 className="page-title">Permits</h1><p className="page-lede">Review permit readiness, coordination holds, NOC requirements and restoration deposits.</p></div><Button onClick={()=>setShowApply(!showApply)}>Apply for permit</Button></div>{error&&<ErrorState onRetry={()=>void load()}/>}<Tabs items={statuses.map(s=>({id:s,label:s.replaceAll('_',' ')}))} value={tab} onChange={setTab}/>
 {showApply&&<Card className="staff-apply-card"><h2>New permit application</h2><p>Select a registered work with its geometry and schedule already recorded.</p><div className="form-field"><label className="form-label">Registered work</label><Select value={workId} onChange={e=>setWorkId(e.target.value)}><option value="">Choose a work</option>{works.map(w=><option key={w.id} value={w.id}>{w.ref_no} · {w.title} · {w.road_name||'Location'}</option>)}</Select></div><div className="form-field"><label className="form-label">Permit type</label><Select value={type} onChange={e=>setType(e.target.value)}><option value="road_cut">Road cut</option><option value="row_utility">Right of way utility</option><option value="closure_noc">Closure NOC</option></Select></div><div className="date-grid"><label className="form-field"><span className="form-label">Valid from</span><Input type="date" value={from} onChange={e=>setFrom(e.target.value)}/></label><label className="form-field"><span className="form-label">Valid to</span><Input type="date" value={to} onChange={e=>setTo(e.target.value)}/></label></div><div className="form-field"><label className="form-label">Application note</label><Textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)}/></div><div className="link-row"><Button disabled={busy||!workId} onClick={()=>void apply()}>Submit application</Button><Button tone="quiet" onClick={()=>setShowApply(false)}>Cancel</Button></div></Card>}
 <div className="staff-list">{!items.length?<Card><EmptyState title={`No ${tab.replaceAll('_',' ')} permits`} detail="Permit applications for registered works will appear here."/></Card>:items.map(p=><Card key={p.id} className="staff-permit-card"><div className="staff-ticket-top"><Badge>{p.type.replaceAll('_',' ')}</Badge><Badge tone={p.status==='pending_coordination'?'warning':'neutral'}>{p.status.replaceAll('_',' ')}</Badge></div><h2>{p.work_ref_no} · {p.work_title}</h2><p>{p.agency_name} · {p.valid_from||'Dates pending'} → {p.valid_to||'Dates pending'}</p>{p.has_open_conflict&&<p className="staff-alert">Approval blocked: {p.conflict_summary||'an open utility conflict involves this work'}. Resolve coordination first.</p>}<p>Deposit: {p.deposit_amount==null?'Not set':`₹${p.deposit_amount.toLocaleString('en-IN')}`} · {p.deposit_status}</p><Link className="ui-button ui-button-secondary" href={`/staff/permits/${p.id}`}>Review permit</Link></Card>)}</div></main>
}
