'use client';
import Link from 'next/link';
import { useQuery } from '@tanstack/react-query';
import { api } from '@/lib/api';
import { useT } from '@/lib/i18n';
import { Badge, Card, ErrorState, LastUpdated, Skeleton } from '@/components/ui';
type Summary={by_status?:Record<string,number>;by_ward?:{ward:string;count:number}[];by_agency?:{agency:string;count:number}[];delayed_count?:number;overdue_updates_count?:number;open_conflicts?:number;repeat_dig_segments?:number;feedback?:{open:number;overdue:number};last_updated_at?:string};
export default function Dashboard(){const {t}=useT();const query=useQuery({queryKey:['summary'],queryFn:()=>api<Summary>('/reports/summary')});if(query.isLoading)return <main className="page-wrap"><Skeleton className="skeleton-card"/></main>;if(query.isError||!query.data)return <main className="page-wrap"><ErrorState onRetry={()=>query.refetch()}/></main>;const data=query.data;return <main className="page-wrap"><span className="eyebrow">Demo City</span><h1 className="page-title">{t('dashboard')}</h1><p className="page-lede">{t('citySummary')}</p><div className="quick-stats"><Stat title={t('ongoing')} value={data.by_status?.ongoing??0}/><Stat title={t('delayed')} value={data.delayed_count??0} alert/><Stat title={t('updateOverdue')} value={data.overdue_updates_count??0} alert/><Stat title={t('openConflicts')} value={data.open_conflicts??0}/><Stat title={t('repeatDig')} value={data.repeat_dig_segments??0}/><Stat title={t('feedbackOpen')} value={data.feedback?.open??0}/></div><div className="section-head"><h2>{t('byStatus')}</h2></div><Card className="status-summary">{Object.entries(data.by_status??{}).map(([status,count])=><Link key={status} href={`/works?status=${status}`}><Badge>{t(status as any)} · {count}</Badge></Link>)}</Card>{data.by_ward?.length&&<><div className="section-head"><h2>{t('byWard')}</h2></div><Card><div className="table-responsive"><table className="summary-table"><thead><tr><th>{t('ward')}</th><th>{t('works')}</th></tr></thead><tbody>{data.by_ward.map((item,index)=><tr key={index}><td>{item.ward}</td><td>{item.count}</td></tr>)}</tbody></table></div></Card></>}<LastUpdated value={data.last_updated_at}/></main>;}
function Stat({title,value,alert=false}:{title:string;value:number;alert?:boolean}){return <Card className="stat-card"><span className={`stat-icon ${alert?'stat-delay':'stat-current'}`}>{title}</span><strong>{value}</strong></Card>}
